[theme]
primaryColor = "#3498DB"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2C3E50"
textColor = "#E0E0E0"
font = "sans serif"

[server]
maxUploadSize = 15

[browser]
gatherUsageStats = false 